import { motion } from 'framer-motion';
import moment from 'moment';
import Image from "next/image";
import React, { useRef } from 'react';
import { CiSettings } from "react-icons/ci";
import { useSelector } from 'react-redux';
import Entry from '../../utils/Entry';
import { useDownloadExcel } from 'react-export-table-to-excel';
import { useReactToPrint } from 'react-to-print';

const Transection_Export = ({ view, setView }) => {
    const { entries, currentBook } = useSelector(state => state.book)
    const EntryManager = new Entry(entries)
    const lastEntry = EntryManager.generatedEntry()[0]
    const printRef = useRef()
    const excelRef = useRef()
    const handlePrint = useReactToPrint({
        content: () => printRef.current,
        documentTitle: currentBook?.name
    });

    const { onDownload } = useDownloadExcel({
        currentTableRef: excelRef.current,
        filename: currentBook?.name,
        sheet: currentBook?.name
    });
    return (
        <>
            <div
                className='fixed -top-2 md:-top-5 left-0 h-screen w-full flex justify-end bg-slate-900/50 z-50'
            >
                <motion.div
                    initial={{
                        x: 500,
                    }}
                    animate={{
                        x: 0
                    }}
                    transition={{
                        duration: 0.3
                    }}
                    className='h-screen w-full md:w-10/12 flex flex-col justify-between bg-white shadow-md'
                >
                    <div
                        className='h-16 px-6 flex justify-between items-center border-b'
                    >
                        <h2 className='text-xl'>Add New Business</h2>
                        <button
                            onClick={() => setView(!view)}
                            className='px-4 py-1 border rounded-md'
                        >
                            X
                        </button>
                    </div>
                    <div
                        style={{ height: 'calc(100vh - 144px)' }}
                        className='px-6 py-4 space-y-6 overflow-y-auto'
                    >
                        <div
                            className='flex justify-between items-center'
                        >
                            <p
                                className='text-3xl'
                            >
                                Preview
                            </p>
                            <button
                                className='px-6 py-2 flex items-center space-x-2 border hover:border-[#4863D4] text-[#4863D4] rounded-md'
                            >
                                <CiSettings size={20} />
                                <span>PDF Settings</span>
                            </button>
                        </div>
                        <div
                            className='p-10'
                        >
                            <div
                                ref={printRef}
                                className='border rounded-md print:m-5 print:border-none'
                            >
                                {/* header */}
                                <div
                                    className='px-4 py-2 flex items-center space-x-3 bg-[#F2F5FF] rounded-t-md'
                                >
                                    <div>
                                        <Image
                                            src='/logo.svg'
                                            alt="logo"
                                            className=""
                                            height={30}
                                            width={80}
                                        />
                                    </div>
                                    <div>
                                        <p className='text-2xl print:text-xl font-bold'>CashBook Report</p>
                                        <p
                                            className='text-sm'
                                        >
                                            Generated On - 08 Mar 2024, 6:06 PM.Generated by - Robiul Awal (+8801717642515)
                                        </p>
                                    </div>
                                </div>
                                {/* transections */}
                                <div
                                    className='px-6 py-4 space-y-5'
                                >
                                    {/* balance */}
                                    <div
                                        className='space-y-2'
                                    >
                                        <p className='text-2xl print:text-xl font-bold'>{currentBook?.name}</p>
                                        <div
                                            className='grid grid-cols-3 border-2 rounded-md print:border-[0.05px]'
                                        >
                                            <div
                                                className='p-2 border-r-2 print:border-r-[0.05px]'
                                            >
                                                <p className='text-sm text-gray-500'>Total Cash In</p>
                                                <p className='text-green-600 font-bold'>{EntryManager.cashIn()}</p>
                                            </div>
                                            <div
                                                className='p-2 border-r-2 print:border-r-[0.05px]'
                                            >
                                                <p className='text-sm text-gray-500'>Total Cash Out</p>
                                                <p className='text-red-600 font-bold'>{EntryManager.cashOut()}</p>
                                            </div>
                                            <div
                                                className='p-2'
                                            >
                                                <p className='text-sm text-gray-500'>Final Balance</p>
                                                <p className='font-bold'>{EntryManager.balance()}</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div
                                        className='space-y-3 pb-10'
                                    >
                                        <p>Total No. of entries: {entries?.length}</p>
                                        <div
                                            className='w-full overflow-x-auto'
                                        >
                                            <table
                                                ref={excelRef}
                                                className='w-full print:text-[12px]'
                                            >
                                                <thead>
                                                    <tr
                                                        className='bg-[#F2F5FF] '
                                                    >
                                                        <td className='p-2 border'>Date</td>
                                                        <td className='p-2 border'>Remark</td>
                                                        <td className='p-2 border'>Contact</td>
                                                        <td className='p-2 border'>Category</td>
                                                        <td className='p-2 border'>Mode</td>
                                                        <td className='p-2 text-right border'>Cash In</td>
                                                        <td className='p-2 text-right border'>Cash Out</td>
                                                        <td className='p-2 border'>Entry By</td>
                                                        <td className='p-2 text-right border'>Balance</td>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {
                                                        EntryManager.generatedEntry().map(entry =>
                                                            <tr
                                                                key={entry?._id}
                                                            >
                                                                <td className='p-2 border'>{moment(entry?.createdAt).format('DD MMM YYYY')}</td>
                                                                <td className='p-2 border'>{entry?.remark}</td>
                                                                <td className='p-2 border'>{entry?.contact?.name}</td>
                                                                <td className='p-2 border'>{entry?.category?.name}</td>
                                                                <td className='p-2 border'>{entry?.payment?.name}</td>
                                                                <td className='p-2 border text-right'>{entry?.entryType === 'cash_in' && entry?.amount}</td>
                                                                <td className='p-2 border text-right'>{entry?.entryType === 'cash_out' && entry?.amount}</td>
                                                                <td className='p-2 border'>{entry?.user?.name}</td>
                                                                <td className='p-2 border text-right'>{entry?.stock}</td>
                                                            </tr>
                                                        )
                                                    }
                                                    <tr
                                                        className='bg-[#F2F5FF] font-bold'
                                                    >
                                                        <td className='p-2 border'>{moment(lastEntry?.createdAt).format('DD MMM YYYY')}</td>
                                                        <td className='p-2 border'>Final Balance</td>
                                                        <td className='p-2 border'></td>
                                                        <td className='p-2 border'></td>
                                                        <td className='p-2 border'></td>
                                                        <td className='p-2 text-right border'>{EntryManager.cashIn()}</td>
                                                        <td className='p-2 text-right border'>{EntryManager.cashOut()}</td>
                                                        <td className='p-2 border'></td>
                                                        <td className='p-2 text-right border'>{EntryManager.balance()}</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div
                        className='h-20 px-6 flex justify-end items-center border-t'
                    >
                        <button
                            onClick={handlePrint}
                            className='px-6 py-3 bg-[#4863D4] text-white rounded-md'
                        >
                            Download PDF
                        </button>
                    </div>
                </motion.div>
            </div>
        </>
    );
};

export default Transection_Export;